import type { Language, MenuItem, MenuResult, RawData } from '../types.ts';
import { HQS, distanceWording, hqName } from '../hq.ts';
import { nowInZurich } from '../util/date.ts';

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function languageBadge(language: Language): string {
  if (language === 'unknown') return '';
  return `<span class="lang-badge" title="source language">${escapeHtml(language.toUpperCase())}</span>`;
}

function renderItem(item: MenuItem): string {
  const parts: string[] = [];
  parts.push(
    `<div class="item-head"><span class="item-name">${escapeHtml(item.name)}</span>${languageBadge(item.language)}</div>`,
  );
  if (item.description) {
    parts.push(`<p class="item-desc">${escapeHtml(item.description)}</p>`);
  }
  const meta: string[] = [];
  if (item.price) meta.push(`<span class="item-price">${escapeHtml(item.price)}</span>`);
  if (item.tags && item.tags.length > 0) {
    meta.push(
      item.tags
        .map((t) => `<span class="item-tag">${escapeHtml(t)}</span>`)
        .join(''),
    );
  }
  if (meta.length > 0) parts.push(`<div class="item-meta">${meta.join('')}</div>`);
  return `<li class="item">${parts.join('')}</li>`;
}

function renderDistances(result: MenuResult): string {
  const chips = HQS.map((hq) => {
    const category = result.restaurant.distances[hq.id];
    return `<span class="distance"><span class="hq">${escapeHtml(hqName(hq.id))}</span>: ${escapeHtml(distanceWording(category))}</span>`;
  });
  return `<div class="distances">${chips.join('')}</div>`;
}

function renderBody(result: MenuResult): string {
  switch (result.status) {
    case 'ok':
      return `<ul class="items">${result.items.map(renderItem).join('')}</ul>`;
    case 'no-menu':
      return `<p class="note note-no-menu">No menu published today.</p>`;
    case 'error':
      return `<p class="note note-error">Menu unavailable today.</p>`;
  }
}

function renderRestaurant(result: MenuResult): string {
  const { restaurant } = result;
  const name = restaurant.url
    ? `<a href="${escapeHtml(restaurant.url)}" rel="noopener noreferrer" target="_blank">${escapeHtml(restaurant.name)}</a>`
    : escapeHtml(restaurant.name);
  return `<section class="restaurant restaurant-${escapeHtml(result.status)}">
      <header class="restaurant-head">
        <h2>${name}</h2>
        ${renderDistances(result)}
      </header>
      ${renderBody(result)}
    </section>`;
}

/** Render the full static summary page HTML for the given RawData. */
export function renderHtml(data: RawData): string {
  const updated = nowInZurich(new Date(data.generatedAt));
  const restaurants = data.results.map(renderRestaurant).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Food Assembler — Lunch for ${escapeHtml(data.date)}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main>
    <header class="page-head">
      <h1>🍽️ Today's Lunch</h1>
      <p class="date">${escapeHtml(data.date)}</p>
      <p class="updated">Last updated: ${escapeHtml(updated)}</p>
    </header>
    ${restaurants}
    <footer class="page-foot">
      <p>Generated by Food Assembler · <a href="./data.json">raw data</a></p>
    </footer>
  </main>
</body>
</html>
`;
}
